/*SELECT C.NUMEROCLIENTE AS CODIGO, NOMECLIENTE, PRIMEIRONOMECONTATO, SEXO, LIMITECREDITO
  FROM CLIENTES C;

*//*
SELECT *
  FROM CLIENTES;  */
  
  
  /*
  INSERT INTO `clientes` (`NumeroCliente`, `NomeCliente`, `UltimoNomeContato`, 
  `PrimeiroNomeContato`, `Sexo`, `Telefone`, `Endereco`, `Complemento`, `Cidade`, `Estado`, `CEP`, `Pais`, 
  `NumeroEmpregadoVendedor`, `LimiteCredito`) VALUES
  (500,'YURI JIVAGO MERGULHAO BARRETO', 'BARRETO', 'YURI', 'M', '99999-8888', 'Av. Joao Naves, 1000', null, 'Uberlândia', 
  'MG', '38400-123', 'Brasil', 1370, 2100)*/
  /*
  UPDATE CLIENTES
  SET TELEFONE = '12345-6789'
  WHERE NUMEROCLIENTE = 500;*/
  
  
  /*DELETE FROM CLIENTES 
  WHERE NUMEROCLIENTE = 500
  
SELECT COUNT(*) AS QTD_CLI FROM CLIENTES WHERE SEXO = 'M' AND LIMITECREDITO > 100000;*/


/*
SELECT MIN(PRECOCOMPRA) AS MENOR_COMPRA,

MAX(PRECOCOMPRA) AS MAIOR_COMPRA,

SUM(PRECOCOMPRA) AS TOTALCOMPRA ,

AVG(PRECOCOMPRA) AS MEDIAPRECOCOMPRA ,

COUNT(*) AS TOTALCOMPRA FROM PRODUTOS;


SELECT * FROM(
SELECT 	MAX(PRECOCOMPRA) AS MAIOR_PRECO,
			MAX(QUANTIDADEESTOQUE) AS MAIOR_ESTOQUE,
			MIN(PRECOCOMPRA) AS MENOR_PRECO,	
			AVG(PRECOCOMPRA) AS MEDIA_PRECO,
			COUNT(PRECOCOMPRA) AS QTD_PROD,
			SUM(PRECOCOMPRA) AS TOTAL_PROD,
			NOMELINHA
	FROM PRODUTOS
	GROUP BY NOMELINHA) TABELA2
	WHERE MAIOR_PRECO > 80
	AND MAIOR_ESTOQUE >9000;


SELECT 	MAX(PRECOCOMPRA) AS MAIOR_PRECO,
			MAX(QUANTIDADEESTOQUE) AS MAIOR_ESTOQUE,
			MIN(PRECOCOMPRA) AS MENOR_PRECO,	
			AVG(PRECOCOMPRA) AS MEDIA_PRECO,
			COUNT(PRECOCOMPRA) AS QTD_PROD,
			SUM(PRECOCOMPRA) AS TOTAL_PROD 
	FROM PRODUTOS
;

select * FROM PRODUTOS;*/

/*SELECT * FROM CLIENTES WHERE SEXO = 'F';*/

SELECT * FROM CLIENTES C, EMPREGADOS E;



SELECT * FROM CLIENTES C, EMPREGADOS E
WHERE C.NUMEROEMPREGADOVENDEDOR = E.NUMEROEMPREGADO;

SELECT * FROM CLIENTES C
	INNER JOIN EMPREGADOS E
ON C.NUMEROEMPREGADOVENDEDOR = E.NUMEROEMPREGADO;

SELECT C.*, 
(SELECT  ULTIMONOME FROM EMPREGADOS WHERE C.NUMEROEMPREGADOVENDEDOR = NUMEROEMPREGADO) AS EMPREGADO
FROM CLIENTES C;















SELECT C1-C2 FROM TABELA






